### ISSUE TITLE
Temporary

### ISSUE THREAD

**Issue by MystycTrolls** [NightRaider73/Aerial-Updater#1]
![screen shot 2018-10-22 at 1 52 22 pm](https://user-images.githubusercontent.com/44180668/47318751-be405a80-d601-11e8-8081-2cb6ce7adb5a.png)

THX

**Comment by MystycTrolls** [comment]
Oh and I am learning how to code........ Kinda:)
And tell me if the readme is good, feel free to edit as much as you like, I want this project to work closely with Aerial:)

**Comment by MystycTrolls** [comment]
@glouel I don't know if this is too much to ask but can Collaborator on Aerial, so that I can help label issues and update the readme? 
Its fine if you say no. :)

**Comment by glouel** [comment]
> Oh and I am learning how to code........ Kinda:)

Cool !

> And tell me if the readme is good, feel free to edit as much as you like, I want this project to work closely with Aerial:)

It looks pretty good so far, thanks ! I added your screenshot, in order to do that FYI, you need to add the screenshot to an issue, then edit the issue to grab the link `![screen shot 2018-10-22 at 1 52 22 pm](https://user-images.githubusercontent.com/44180668/47318751-be405a80-d601-11e8-8081-2cb6ce7adb5a.png)`
then you can paste it in readme :)

> @glouel I don't know if this is too much to ask but can Collaborator on Aerial, so that I can help label issues and update the readme?
> Its fine if you say no. :)

I had a look but as far as I know I can't do that since I don't own the repository, sorry.

**Comment by NightRaider73** [comment]
Can you ask JohnCoats?

**Comment by MystycTrolls** [comment]
@glouel Can you ask JohnCoates?

**Comment by MystycTrolls** [comment]
Also where is the best place to start to learn swift?

**Comment by glouel** [comment]
> @glouel Can you ask JohnCoates?

I'll try to get in touch with him yeah, he's not around much.

> Also where is the best place to start to learn swift?

Do you have any experience programming at all  ? If not you might want to start easy with something like https://www.apple.com/swift/playgrounds/

It starts simple but I think it's actually pretty good, it gets you around some important concepts. Getting the basics right makes a huge difference afterwards.

One site that's pretty well known for tutorials is https://www.raywenderlich.com although I haven't looked at those in a while, no idea how good that is. Depending on your experience there might be other options. 

Definitely look into playgrounds first, I'd say !

**Comment by MystycTrolls** [comment]
Thank you so much

**Comment by MystycTrolls** [comment]
@glouel Yeah I have some experience but not much so yeah I will start with Swift Playgrounds.
My hope is that by TVos 14 I will be able to help with the new videos they add.

**Comment by MystycTrolls** [comment]
Should I try to email him?

**Comment by glouel** [comment]
Up to you ! If not I’ll try to reach him. Off for the night here.
